[project]
name = "healt-talk-to"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.09"
dependencies = [
    "asyncio>=3.4.3",
    "ffmpeg>=1.4",
    "ffmpeg-python>=0.2.0",
    "playwright>=1.51.0",
    "tiktokapi>=7.0.0",
]
